version: '3'

services:
  rimgo:
    image: codeberg.org/video-prize-ranch/rimgo # Official image
    #image: quay.io/pussthecatorg/rimgo # Unofficial image
    #build: . # Uncomment to build from source
    ports:
      - 3000:3000
    restart: unless-stopped
    user: 65534:65534 # equivalent to `nobody`
    read_only: true
    security_opt:
      - no-new-privileges: true
    cap_drop:
      - ALL
    networks:
      - rimgo

networks:
  - rimgo